### ISSUE TITLE
Incorrect processing of YAML indentation

### ISSUE THREAD

**Issue by EricVS** [willthames/ansible-review#15]
According to both YAML documentation and Ansible YAML syntax (http://docs.ansible.com/ansible/YAMLSyntax.html), the indentation that gets checked with the function files_should_be_indented is incorrect.
A warning is thrown if I have indentation at the - with a list of tags for example.
```
- name: Create kill link
  file:
    state: link
    src: /opt/uptime-agent/bin/upt_daemon.sh
    dest: /etc/rc.d/rc3.d/K1uptm_daemon
  tags:
    - uptimeconfig
```
```
WARN: Best practice "YAML should be correctly indented" not met:
roles/configure.uptimeagent/tasks/main.yml:11: lines starting with '- ' should have same or less indentation than previous line
```
The warning disappears when I remove the two spaces in front of the dash at the tag, as such. 
```
- name: Create kill link
  file:
    state: link
    src: /opt/uptime-agent/bin/upt_daemon.sh
    dest: /etc/rc.d/rc3.d/K1uptm_daemon
  tags:
  - uptimeconfig
```
This doesn't follow Ansible YAML syntax as per the documentation, though it works apparently without any issues. 

Can you advice on this, if it's intentional or not? Thanks in advance. 

Kind regards, 

Eric V.
