### ISSUE TITLE
Octal Permission representation

### ISSUE THREAD

**Issue by Moumoutaru** [willthames/ansible-review#55]
This:
```
- name: Template Mcrouter config
  template:
    src: mcrouter-config.json.j2
    dest: /etc/mcrouter/mcrouter-config.json
    owner: mcrouter
    group: mcrouter
    mode: 0755
  tags:
    - mcrouter-config
```
becomes:
```
{'delegate_to': None, 'name': 'Template Mcrouter config', 'tags': ['mcrouter-config'], '__file__': 'mcrouter/tasks/mcrouter.yml', '__line__': 44, '__ansible_action_type__': 'task', 'action': {'src': 'mcrouter-config.json.j2', '__ansible_arguments__': [], 'dest': '/etc/mcrouter/mcrouter-config.json', '__ansible_module__': 'template', '__file__': 'mcrouter/tasks/mcrouter.yml', '__line__': 45, 'mode': 493, 'owner': 'mcrouter', 'group': 'mcrouter'}}
```

I was looking to create a lint for octal permissions but their representation in ansible-review seems off.
