### ISSUE TITLE
Support for pre-commit hook `verbose` option

### ISSUE THREAD

**Issue by ansiblejunky** [willthames/ansible-review#83]
Currently when we use the pre-commit hook with `ansible-review` and set the `verbose` option on the hook definition in the `.pre-commit-config.yaml` file the `ansible-review` tool does not react to this option at all - the output of the tool is the same.

I would imagine with `verbose: true`, ansible-review will produce the WARN and ERROR messages.  With `verbose: false`, ansible-review will only show the ERROR messages.

```
---

repos:
  - repo: https://github.com/willthames/ansible-review
    rev: v0.14.0rc2
    hooks:
      - id: ansible-review
        name: ansible-review
        entry: ansible-review -c .ansible-review
        verbose: true
```
